# Generated by Django 5.1.1 on 2024-10-10 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_author_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='selected_category',
        ),
        migrations.AddField(
            model_name='recipes',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.recipes_category'),
            preserve_default=False,
        ),
    ]
