# Generated by Django 5.1.1 on 2024-10-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_sex_user_male'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='male',
            new_name='gender',
        ),
    ]
