# Generated by Django 5.1.1 on 2024-10-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_male_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='recipes_category',
            name='category_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
