# Generated by Django 5.1.1 on 2024-10-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_profile_delete_selection_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.IntegerField(),
        ),
    ]
