# Generated by Django 5.1.1 on 2024-11-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_post_author_delete_author_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название рецепта'),
        ),
    ]
